### ISSUE TITLE
fix: Issue training error with train.py

### ISSUE THREAD

**Issue by nunenuh** [nunenuh/facial-keypoint.pytorch#13]
Trainer Problem :
- trainer.save_checkpoint in train.py module does not works with pytorch lightning version 1.6.5, when it run with that statement it got
`AttributeError: 'NoneType' object has no attribute 'state_dict'`
- `metrics =  trainer.logged_metrics` does not have epoch key anymore, need to use `trainer.current_epoch` as change
- add support for tensorboard logger

Task Problem
- module task.py have a problem with `images,key_pts = batch`, because the dataset return a dictionary, so it need to change to `images, key_pts = batch['image'], batch['keypoints']`
- module task.py does not have `self.learning_rate`, need to add `self.learning_rate = lr`
- module task need to fix metrics with mse and mean metric

DataModule Problem
- fix transform parameter error, change from `transforms=` to `transform=`
